# ---------------------------------------------------------------------------- #
#                             Less layer dockerfile                            #
# ---------------------------------------------------------------------------- #
FROM ubuntu/nginx:latest
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y && apt-get upgrade -y && apt-get install --no-install-recommends vim net-tools dnsutils -y